[project]
name = "pa1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Cristiano Gregory Monfrim Camandaroba", email = "cristianogregorymc@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "torch>=2.3.0",
    "jupyterlab>=4.0.0",
    "tiktoken>=0.5.1",
    "matplotlib>=3.7.1",
    "tensorflow>=2.18.0",
    "tqdm>=4.66.1",
    "numpy>=1.26.0,<2.1.0",
    "pandas>=2.2.1",
    "psutil>=5.9.5",
]

[project.scripts]
pa1 = "pa1:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
